name: Backport
on:
  pull_request_target:
    types:
      - closed

jobs:
  # align with crossplane's choice https://github.com/crossplane/crossplane/blob/master/.github/workflows/backport.yml
  open-pr:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@6ccd57f4c5d15bdc2fef309bd9fb6cc9db2ef1c6
        with:
          fetch-depth: 0

      - name: Open Backport PR
        uses: zeebe-io/backport-action@v0.0.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_workspace: ${{ github.workspace }}
