name: Static Check

on:
  push:
    branches:
      - main
      - release-*
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
      - release-*
env:
  # Common versions
  GO_VERSION: '1.22.0'
  
jobs:
  detect-noop:
    runs-on: ubuntu-22.04
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.mdx", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
          concurrent_skipping: false

  check:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go
    - name: upgrade yarn
      run: yarn set version 3.6.0
    - run: yarn install
    - run: yarn lint
      name: Check Frontend Code Style
    - run: yarn test
    - run: make check-diff
      name: Check Server Code Style
